###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  webserver:
    image: nginx:latest
    container_name: ${PROJECT}_webserver
    working_dir: /application
    volumes:
    - .:/application
    - ./phpdocker/nginx/default.conf:/etc/nginx/includes.d/default.conf
    - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

    ports:
    - "8888:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: ${PROJECT}_php
    working_dir: /application
    volumes:
    - .:/application
    - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
